CREATE TABLE fornecedor (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE conta (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_vencimento DATE,
    data_pagamento  DATE,
    valor           NUMERIC(19, 2) NOT NULL,
    descricao       VARCHAR(255),
    situacao        VARCHAR(20)    NOT NULL,
    fornecedor_id   BIGINT         NOT NULL,
    CONSTRAINT fk_conta_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES fornecedor (id)
);
